# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 12:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 4, 26, 12, 13, 17, 596170, tzinfo=utc), verbose_name='Post date'),
            preserve_default=False,
        ),
    ]
