# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        ('home', '0007_auto_20160426_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='forms.FormPage'),
        ),
    ]
